# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
on:
  schedule:
    - cron:  '0 0 */7 * *'
#   push:
#     branches: [ master ]

jobs:
  update_and_push:

    runs-on: ubuntu-latest
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      run: python run.py
    - name: push Result
      run: |
        git config --global user.email "workflow@example.com"
        git config --global user.name "workflow user"
        git add .
        git commit -m 'update index.html by Github Actions' && git push ${REPO} master || true
